INSERT INTO quotes (quote, author) 
VALUES
    ('PERFECT IS THE ENEMY OF GOOD.', 'VOLTAIRE'),
    ('I’M STILL LEARNING.', 'MICHELANGELO'),
    ('LIFE IS A JOURNEY, NOT A DESTINATION.', 'RALPH WALDO EMERSON'),
    ('LEARNING IS NOT ATTAINED BY CHANCE, IT MUST BE SOUGHT FOR WITH ARDOR AND ATTENDED TO WITH DILIGENCE.', 'RALPH WALDO EMERSON'),
    ('YESTERDAY I WAS CLEVER, SO I CHANGED THE WORLD. TODAY I AM WISE, SO I AM CHANGING MYSELF.', 'RUMI'),
    ('BE CURIOUS, NOT JUDGMENTAL.', 'WALT WHITMAN');
